name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Run build script
      run: pwsh ./build.ps1
    - name: Collect artifacts
      uses: actions/upload-artifact@v2
      with:
        name: cinegy-powershell-installmodule
        path: bin/Cinegy.InstallModule
